sudo: required

branches:
  only:
  - master-source

services:
  - docker

before_install:
  - cd ../
  - docker pull sanchom/pollen
  - docker run --rm -v `pwd`:/work -w /work sanchom/pollen raco pollen render -r sanchom.github.io
  - docker run --rm -v `pwd`:/work -w /work sanchom/pollen raco pollen publish sanchom.github.io published

install: skip

before_script: skip

script:
  - ls ../
  - ls
  - ls published

after_success: skip

after_failure: skip

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: published
  target-branch: master
  committer-from-gh: true
  verbose: true
  github-token: $GITHUB_TOKEN

after_script: skip

