sudo: required

language: python

branches:
  only:
  - master-source

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tree

script:
  - cd ../
  - docker pull sanchom/pollen
  - docker run -v `pwd`:/work --name racket_container -d sanchom/pollen tail -f /dev/null
  - docker exec racket_container raco pkg install pollen-citations-mcgill
  - docker exec racket_container bash -c "cd /work/sanchom.github.io && raco test pollen.rkt markdown.rkt util.rkt" || travis_terminate 1;
  - docker exec racket_container bash -c "cd /work && raco pollen render -r sanchom.github.io"
  - docker exec racket_container bash -c "cd /work && raco pollen publish sanchom.github.io published"
  - docker rm -f racket_container

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  allow-empty-commit: true
  local-dir: ../published
  target-branch: master
  committer-from-gh: true
  github-token: $GITHUB_TOKEN
  verbose: true
  on:
    branch: master-source
